server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: paymentuser
    password: securepass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

management:
  server:
    base-path: /internal/actuator
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
