spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-health
          uri: http://localhost:8081
          predicates:
            - Path=/users/internal/actuator/health
          filters:
            - RewritePath=/users/internal/actuator/health, /actuator/health

        - id: payment-health
          uri: http://localhost:8082
          predicates:
            - Path=/payments/internal/actuator/health
          filters:
            - RewritePath=/payments/internal/actuator/health, /actuator/health

        - id: transaction-health
          uri: http://localhost:8083
          predicates:
            - Path=/transactions/internal/actuator/health
          filters:
            - RewritePath=/transactions/internal/actuator/health, /actuator/health

        - id: notification-health
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/internal/actuator/health
          filters:
            - RewritePath=/notifications/internal/actuator/health, /actuator/health

        # Your main service routes
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/transactions/**
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**


    loadbalancer:
      enabled: false
  kubernetes:
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: gateway,health
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080
