resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
spring:
  kafka:
    consumer:
      group-id: transaction-service-group
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: paymentuser
    password: securepass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8082
